Symfony-Bloogt/src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
     /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
     /**
     * @ORM\Column(type="string")
     * @var string
     */
    private $title;


    /**
     * @ORM\OneToMany(targetEntity="PostImage", mappedBy="post", cascade={"all"}, orphanRemoval=true)
     * @ORM\JoinColumn(name="post_id")
     */
    private $imagePost;
    /**
     * @ORM\Column(type="datetime")
     * @var DateTime
     */
    private $createdAt;
     /**
     * @ORM\Column(type="text")
     * @Assert\NotNull()
     * @var string
     */
    private $content;

  /**
     * @ORM\ManyToMany(targetEntity="Hashtag", mappedBy="posts")
     */
    private $hashtags;

    /**
     * @ORM\OneToMany(targetEntity="Comments", mappedBy="post", cascade={"all"}, orphanRemoval=true)
     * @ORM\JoinColumn(name="comment_id", onDelete="CASCADE")
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $createdBy;
    /**
     * @ORM\ManyToOne(targetEntity="Category")
     */
    private $category;
     /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $timesViewed;

    /**
     * @ORM\OneToMany(targetEntity="PostReaction", mappedBy="post", cascade={"all"}, orphanRemoval=true)
     * @ORM\JoinColumn(name="post_id", onDelete="CASCADE")
     */
    private $reaction;

    /**
     * @ORM\OneToMany(targetEntity="Notifications", cascade={"all"},  mappedBy="relatedComment", orphanRemoval=true)
     * @ORM\JoinColumn(name="post_id", onDelete="CASCADE")
     */
    private $notifications;


    ////////////////    Only for shared Posts

    public $isShared;
    public $sharedBy;
    public $sharedAt;

    ////////////////////////////////////////////////////////////////////////////////////////////////////
    ///                 GETTERS AND SETTERS
    ///

    public function __construct()
    {


        $this->setTimesViewed(0);
        $this->createdAt = new \DateTime("now");
    }


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getImagePost()
    {
        return $this->imagePost;
    }

    /**
     * @param mixed $imagePost
     */
    public function setImagePost($imagePost): void
    {
        $this->imagePost = $imagePost;
    }

    /**
     * @return String
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt->format('Y-m-d h:m:s');
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * @return mixed
     */
    public function getHashtags()
    {
        return $this->hashtags;
    }

    /**
     * @param mixed $hashtags
     */
    public function setHashtags($hashtags): void
    {
        $this->hashtags = $hashtags;
    }

    /**
     * @return mixed
     */
    public function getComments()
    {
        return $this->comments;
    }
    /**
     * @return number
     */
    public function getCommentCount()
    {
        if($this->comments ==null)
            return 0;
        return sizeof($this->comments);
    }

    /**
     * @param mixed $comments
     */
    public function setComments($comments): void
    {
        $this->comments = $comments;
    }

    /**
     * @return mixed
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param mixed $createdBy
     */
    public function setCreatedBy($createdBy): void
    {
        $this->createdBy = $createdBy;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category): void
    {
        $this->category = $category;
    }

    /**
     * @return int
     */
    public function getTimesViewed(): int
    {
        return $this->timesViewed;
    }

    /**
     * @param int $timesViewed
     */
    public function setTimesViewed(int $timesViewed): void
    {
        $this->timesViewed = $timesViewed;
    }

    /**
     * @return mixed
     */
    public function getReaction()
    {
        return $this->reaction;
    }

    /**
     * @return number
     */
    public function getReactionCount()
    {
        return sizeof($this->reaction);
    }

    /**
     * @return number
     */
    public function getPositiveReactionCount()
    {
        $positiveReactionCount = 0;
        foreach ($this->reaction as $dat){
            if($dat->isReaction() == true){
                $positiveReactionCount++;
            }
        }
        return $positiveReactionCount;
    }

    /**
     * @return number
     */
    public function getNegativeReactionCount()
    {
        $negativeReactionCount = 0;
        foreach ($this->reaction as $dat){
            if($dat->isReaction() == false){
                $negativeReactionCount++;
            }
        }
        return $negativeReactionCount;
    }

    /**
     * @param mixed $reaction
     */
    public function setReaction($reaction): void
    {
        $this->reaction = $reaction;
    }

    /**
     * @return mixed
     */
    public function getIsShared()
    {
        return $this->isShared;
    }

    /**
     * @param mixed $isShared
     */
    public function setIsShared($isShared): void
    {
        $this->isShared = $isShared;
    }

    /**
     * @return mixed
     */
    public function getSharedBy()
    {
        return $this->sharedBy;
    }

    /**
     * @param mixed $sharedBy
     */
    public function setSharedBy($sharedBy): void
    {
        $this->sharedBy = $sharedBy;
    }

    /**
     * @return mixed
     */
    public function getSharedAt()
    {
        return $this->sharedAt;
    }

    /**
     * @param mixed $sharedAt
     */
    public function setSharedAt($sharedAt): void
    {
        $this->sharedAt = $sharedAt;
    }




    /////////////////////////////////////////////////////////////////////////////////////////////////////
    ///         DATA PROJECTIONS
    ///

    public static function MapDataToPostMinDataProjection($data){
        if(is_array($data)  or $data instanceof \Doctrine\ORM\PersistentCollection){
            $dataToReturn = array();
            foreach($data as $dat) {
                $dataToReturn[] = Post::PostMinData($dat);
            }
            return $dataToReturn;
        }else{
            return Post::PostMinData($data);
        }
    }
    public static function MapDataToPostDataProjection($data){
        if(is_array($data)  or $data instanceof \Doctrine\ORM\PersistentCollection){
            $dataToReturn = array();
            foreach($data as $dat) {
                $dataToReturn[] = Post::PostData($dat);
            }
            return $dataToReturn;
        }else{
            return Post::PostData($data);
        }
    }


    public static function PostMinData($Post){

        $data =[
            'id' => $Post->getId(),
            'title' => $Post->getTitle(),
            'createdBy' => User::MapDataToUserBasicDataProjection($Post->getCreatedBy()),
            'createdAt' => $Post->getCreatedAt(),
            'totalReactions' => $Post->getReactionCount(),
            'negativeReactions' => $Post->getNegativeReactionCount(),
            'positiveReactions' => $Post->getPositiveReactionCount(),

        ];
        return $data;
    }
    public static function PostData($Post){

        $data =[
            'id' => $Post->getId(),
            'content' => $Post->getContent(),
            'title' => $Post->getTitle(),
            'createdBy' => User::MapDataToUserBasicDataProjection($Post->getCreatedBy()),
            'createdAt' => $Post->getCreatedAt(),
            'totalReactions' => $Post->getReactionCount(),
            'negativeReactions' => $Post->getNegativeReactionCount(),
            'positiveReactions' => $Post->getPositiveReactionCount(),
            'comentaryCount' => sizeof($Post->getComments()),
            'timesViewed' => 9999,
            'category' => Category::MapDataCategoryOnlyNameProjection($Post->getCategory()),
            'isShared' => null,
            'sharedBy' => null,
            'sharedAt' => null,
    //        'imagePost' => PostImagePost::PostImageList($Post->getImagePost()),
            'hashtags' => Hashtag::MapDataHashtagOnlyNameProjection($Post->getHashtags())

        ];
        return $data;
    }


}

Symfony-Bloogt/templates/adminTables/categoriesCreation.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}

    <div class="card text-white bg-secondary mb-3">
        <div class="card-header">Create Category</div>
        <div class="card-body">
            <div class="card-text">
                <form action="/admin/newCategory">
                    <!--
                    <label for="category">Create new Category: </label>
                    -->
                    <input class="form-control" type="text" id="category" name="category"/>
                    <input class="btn btn-secondary btn-lg btn-block" type="submit" value="New Category">
                </form>
            </div>
        </div>
    </div>

    <div class="createCategory form-group">

    </div>



<table class="table  table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Category name</th>
        <th>Post count</th>
        <th>Delete category</th>


    </tr>
    </thead>

    <tbody>
{% for category in categories %}
    <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.getPostCount }}</td>
        <td><a href="{{ path('deleteCategory', {id: category.id}) }}"><i class="glyphicon glyphicon-remove"></i></a></td>

    </tr>
{% endfor %}
    </tbody>

</table>

{% endblock %}

Symfony-Bloogt/templates/adminTables/categoriesList.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}
    <!--
    <div class="createCategory form-group">
        <form action="/admin/newCategory">
            <label for="category">Create new Category: </label>
            <input class="form-control" type="text" id="category" name="category"/>
            <input class="btn btn-secondary btn-lg btn-block" type="submit" value="New Category">

        </form>

    </div>
    -->
<table class="table  table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Category name</th>
        <th>Post count</th>
        <th>Delete category</th>


    </tr>
    </thead>

    <tbody>
{% for category in categories %}
    <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.getPostCount }}</td>
        <td><a href="{{ path('deleteCategory', {id: category.id}) }}"><i class="glyphicon glyphicon-remove"></i></a></td>

    </tr>
{% endfor %}
    </tbody>

</table>

{% endblock %}

Symfony-Bloogt/templates/adminTables/commentList.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}
<table class="table  table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Message</th>
        <th>Created at</th>
        <th>Post related</th>


    </tr>
    </thead>

    <tbody>
{% for comment in comments %}
    <tr>

        <td>{{ comment.getMessage() }}</td>
        <td>{{ comment.getCreatedAt() }}</td>
        <td><a>View post</a></td>

    </tr>
{% endfor %}
    </tbody>

</table>

{% endblock %}

Symfony-Bloogt/templates/adminTables/createRandomComments.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}

    <div class="card text-white bg-secondary mb-3">
        <div class="card-header">Create random comments</div>
        <div class="card-body">
            <div class="card-title">Number of created comments:</div>

            <div class="card-text">
                <form method="GET">
                    <input class="btn-block" type="text" placeholder="10" name="numberOfComments"/>
                    <input type="submit" value="create" class="btn btn-block btn-dark"/>

                </form>

            </div>
        </div>
    </div>

{% endblock %}

Symfony-Bloogt/templates/adminTables/createRandomPosts.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}

    <div class="card text-white bg-secondary mb-3">
        <div class="card-header">Create random posts of random users</div>
        <div class="card-body">
            <div class="card-title">Number of created posts:</div>

            <div class="card-text">
                <form method="GET">
                    <input class="btn-block" type="text"  placeholder="10" name="numberOfPosts"/>
                    <input type="submit" value="create" class="btn btn-block btn-dark"/>

                </form>

            </div>
        </div>
    </div>

{% endblock %}

Symfony-Bloogt/templates/adminTables/createRandomUsers.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}

    <div class="card text-white bg-secondary mb-3">
        <div class="card-header">Create random users</div>
        <div class="card-body">
            <div class="card-title">Number of created users:</div>

            <div class="card-text">
                <form method="GET">
                    <input class="btn-block" type="text"  placeholder="10" name="numberOfUsers"/>
                    <input type="submit" value="create" class="btn btn-block btn-dark"/>

                </form>

            </div>
        </div>
    </div>

{% endblock %}

Symfony-Bloogt/templates/adminTables/mainLayout.html.twig
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Symfony Bloogt</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">




    {% block stylesheets %}
        {# 'app' must match the first argument to addEntry() in webpack.config.js #}
        {{ encore_entry_link_tags('app') }}

        <!-- Renders a link tag (if your module requires any CSS)
             <link rel="stylesheet" href="/build/app.css"> -->
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}

        <!-- Renders app.js & a webpack runtime.js file
            <script src="/build/runtime.js" defer></script>
            <script src="/build/app.js" defer></script>
            See note below about the "defer" attribute -->
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">
</head>

<body>

<header>

    {% include 'main/common/header.html.twig' %}

</header>
{% for flash_message in app.session.flashbag.get('success') %}
    <div class="flash-success alert alert-primary" >
        {{ flash_message }}
    </div>
{% endfor %}

{% for flash_message in app.session.flashbag.get('error') %}
    <div class="flash-error alert alert-primary" >
        {{ flash_message }}
    </div>
{% endfor %}
<div id="Wrapper">
    <div class="wrapper">
        <div class="subHeader">
            {% include 'main/common/subHeader.html.twig' %}
        </div>

        <div class="col-2 float-left">
            {% include 'adminTables/sideBar.html.twig' %}
        </div>
        <div class="">
            <div class="col-10 float-right ">
                {% block body %}

                {% endblock %}
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>

</html>

Symfony-Bloogt/templates/adminTables/postList.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}
<table class="table  table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Category</th>
        <th>Reaction count</th>
        <th>Creation date</th>
        <th>Content</th>
        <th>CommentCount</th>
        <th>Hashtags</th>
        <th>Delete</th>


    </tr>
    </thead>

    <tbody>
{% for post in posts %}

    

    <tr>
        <td>{{ post.getCategory().getName() }}</td>
        <td>{{ post.reactionCount }}</td>
        <td>{{ post.createdAt() }}</td>
        <td>{{ post.getContent() }}</td>
        <td>{{ post.getCommentCount() }}</td>
        <td>

            {% for hashtag in post.getHashtags() %}
                #{{ hashtag.getName()|e }}
                <br/>

            {% endfor %}

        </td>

        <td><a href="{{ path('deletePost', {id: post.id}) }}"><i class="glyphicon glyphicon-remove"></i></a></td>
    </tr>
{% endfor %}
    </tbody>

</table>

{% endblock %}

Symfony-Bloogt/templates/adminTables/routesTable.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}
<table class="table  table-striped">
    <thead class="thead-dark">
    <tr>
        <th>Routes</th>
        <th>Methods</th>
        <th>Status</th>

    </tr>
    </thead>

    <tbody>
{% for route in routes %}
    <tr>
   <td> {{ route.getPath()|e }}</td>
   <td>
       {% for method in route.methods %}
       {{ method|e }}

       {% endfor %}

   </td>
    </tr>
{% endfor %}
    </tbody>
</table>

{% endblock %}

Symfony-Bloogt/templates/adminTables/sideBar.html.twig
<div class="sidebar">

    <h2 class="list-group-item text-light bg-dark mt-3">List data</h2>
    <ul class="list-group">
        <a href="{{ path('listAllApiMethods') }}"><li class="list-group-item list-group-item-action">List Rest api methods</li></a>
        <a href="{{ path('listAllUsers') }}"><li class="list-group-item list-group-item-action">List all users</li></a>
        <a href="{{ path('listAllPosts') }}"><li class="list-group-item list-group-item-action">List all posts</li></a>
        <a href="{{ path('listAllComments') }}"><li class="list-group-item list-group-item-action">List all comments</li></a>
        <a href="{{ path('listAllCategories') }}"><li class="list-group-item list-group-item-action">List all categories</li></a>

    </ul>

    <h2 class="list-group-item text-light bg-dark  mt-5">Create</h2>
    <a href="{{ path('createCategories') }}"><li class=" list-group-item list-group-item-action">Create categories</li></a>
    <a href="{{ path('createRandomUsers') }}"><li class=" list-group-item list-group-item-action">Random users</li></a>
    <a href="{{ path('createRandomPosts') }}"><li class=" list-group-item list-group-item-action">Random posts</li></a>
    <a href="{{ path('createRandomComments') }}"><li class=" list-group-item list-group-item-action">Random comments</li></a>

</div>

Symfony-Bloogt/templates/adminTables/userList.html.twig
{% extends "adminTables/mainLayout.html.twig" %}

{% block body %}
<table class="table  table-striped">
    <thead class="thead-dark">
    <tr>
        <th></th>
        <th>Username</th>
        <th>Email</th>
        <th>Roles</th>
        <th>Posts</th>
        <th>Comments</th>
        <th>Following</th>
        <th>Followers</th>
        <th>Delete user</th>

    </tr>
    </thead>

    <tbody>
{% for user in users %}
    <tr>
        <td>
            <img height="50" src="{{ user.getAvatar()|e }}"/>
            </td>


   <td> <a href="{{ path('profile', {username: user.getUsername}) }}">{{ user.getUsername()|e }}</a></td>

        <td> {{ user.getEmail()|e }}</td>
   <td>

       {% for roles in user.getRoles() %}
           {{ roles|e }}
   <br/>

       {% endfor %}

   </td>
        <td><a href="{{ path('listPostsOfUser', {username: user.getUsername()}) }}">{{ user.getPostNumber() }}</a></td>
        <td><a href="{{ path('listCommentsOfUser', {username: user.getUsername()}) }}">{{ user.getCommentCount() }}</a></td>
        <td>{{ user.getFollowingCount() }}</td>
        <td></td>
        <td><a href="{{ path('deleteUser', {id: user.id}) }}"><i class="glyphicon glyphicon-remove"></i></a></td>
    </tr>
{% endfor %}
    </tbody>
</table>

{% endblock %}