Symfony-Bloogt/src/Entity/Chat.php
<?php

namespace App\Entity;

use App\Entity\User as User;
use App\Repository\ChatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatRepository::class)
 */
class Chat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\OneToMany(targetEntity="Message", mappedBy="chat", cascade={"all"}, orphanRemoval=true)
     * @ORM\JoinColumn(name="message_id")
     */
    private $messages;
     /**
     * @ORM\Column(type="datetime")
     * @var DateTime
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="chats" )
     * @var User[]
     */
    private $usersInvolved;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Message[]
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * @return mixed
     */
    public function getLastMessage()
    {

        foreach($this->getMessages() as $message);
        return $message;
    }



    /**
     * @param mixed $messages
     */
    public function setMessages($messages): void
    {
        $this->messages = $messages;
    }

    /**
     * @return string
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt->format('Y-m-d h:m:s');
    }

    /**
     * @param DateTime $createdAt
     */
    public function setCreatedAt(DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return Users[]
     */
    public function getUsersInvolved()
    {
        return $this->usersInvolved;
    }

    /**
     * @param mixed $usersInvolved
     */
    public function setUsersInvolved($usersInvolved): void
    {
        $this->usersInvolved = $usersInvolved;
    }

    /**
     * @param string $username
     * @return User|null
     */
    public function getUserExcept(string $username)
    {

        foreach($this->getUsersInvolved() as $user){

            if($user->getUsername() != $username){
                return $user;
            }
        }

        return null;
    }

    public function __construct()
    {
        $this->createdAt = new \DateTime("now");
    }



}

Symfony-Bloogt/templates/main/routes/account/accountAportations.html.twig
{% extends "main/routes/account/accountLayout.html.twig" %}


{% block body %}
    {% include 'main/common/postList.html.twig' %}
{% endblock %}

Symfony-Bloogt/templates/main/routes/account/accountEdit.html.twig
{% extends "main/routes/account/accountLayout.html.twig" %}


{% block body %}

    <div class="card text-center">
        <div class="card-header">
            Edit user data
        </div>
        <div class="card-body">

            <div class="container">
                <div class="col-2 float-left" >

                    {% if User.avatar == null %}
                        <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"  alt="Admin" class="rounded-circle" width="150">
                    {% endif %}

                    {% if User.avatar != null %}
                        <img src="{{User.avatar}}"  alt="Admin" class="rounded-circle" width="150">
                    {% endif %}

                </div>
                <div class="editDataForm col-10 float-right">
                <form method="POST" action="{{ path('accountEditForm') }}">

                    <div class="form-group">
                        <label for="avatar">Avatar</label>
                        <input class="form-control" type="text" name="avatar"  id="avatar" placeholder="{{ User.avatar }}"/>
                    </div>

                    <div class="form-group">
                        <label for="username">Username</label>
                        <input class="form-control" type="text" name="username"  id="username" placeholder="{{ User.username }}"/>
                    </div>

                    <div class="form-group">
                        <label for="name">Name</label>
                        <input class="form-control" type="text" name="name" id="name" placeholder="{{ User.name }}"/>
                    </div>

                    <div class="form-group">
                        <label for="surname">Surname</label>
                        <input class="form-control" type="text" name="surname"  id="surname" placeholder="{{ User.surname }}"/>
                    </div>

                    <div class="form-group">
                        <label for="email">Email</label>
                        <input class="form-control" type="text"  name="email" id="email" placeholder="{{ User.email }}"/>
                    </div>

                    <div class="form-group">
                        <label for="bio">Bio</label>
                        <input class="form-control" type="text" name="bio"  id="bio" placeholder="{{ User.bio }}"/>
                    </div>

                    <div class="form-group">
                        <label for="password">Old password</label>
                        <input class="form-control" type="password" name="oldPassword"  id="oldPassword"/>
                    </div>

                    <div class="form-group">
                        <label for="newPassword">New password</label>
                        <input class="form-control" type="password"  name="newPassword" id="newPassword"/>
                    </div>

                    <div class="form-group">
                        <label for="repeatNewPassword">Repeat new password</label>
                        <input class="form-control" type="password"  name="repeatNewPassword" id="repeatNewPassword"/>
                    </div>


                    <button type="submit" class="btn btn-primary">Edit data user</button>
                </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

Symfony-Bloogt/templates/main/routes/account/accountIndex.html.twig
{% extends "main/routes/account/accountLayout.html.twig" %}


{% block body %}
    {% include 'main/common/postList.html.twig' %}


{% endblock %}

Symfony-Bloogt/templates/main/routes/account/accountLayout.html.twig
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Symfony Bloogt</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">



    {% block stylesheets %}
        {# 'app' must match the first argument to addEntry() in webpack.config.js #}
        {{ encore_entry_link_tags('app') }}

        <!-- Renders a link tag (if your module requires any CSS)
             <link rel="stylesheet" href="/build/app.css"> -->
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}

        <!-- Renders app.js & a webpack runtime.js file
            <script src="/build/runtime.js" defer></script>
            <script src="/build/app.js" defer></script>
            See note below about the "defer" attribute -->
    {% endblock %}


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">
</head>

<body>

<header>

        {% include 'main/routes/account/header.html.twig' %}

</header>
{% for flash_message in app.session.flashbag.get('success') %}
    <div class="flash-success alert alert-primary" >
        {{ flash_message }}
    </div>
{% endfor %}

{% for flash_message in app.session.flashbag.get('error') %}
    <div class="flash-error alert alert-danger" >
        {{ flash_message }}
    </div>
{% endfor %}


<div id="Wrapper">
    <div class="wrapper">

<div class="subHeader">
        {% include 'main/routes/account/subHeader.html.twig' %}
</div>
        <div class="col-9 mainContent float-left">
        {% block body %}

        {% endblock %}
        </div>
        <div class="col-3 mainSidebar float-right">
            {% include 'main/routes/account/sideBar.html.twig' %}
        </div>
    </div>
</div>

<!--
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
-->
</body>

</html>

Symfony-Bloogt/templates/main/routes/account/accountNetwork.html.twig
{% extends "main/routes/account/accountLayout.html.twig" %}


{% block body %}

    <div class="card bg-light mb-3">
        <div class="card-header">Following</div>
        <div class="card-text">

    {% for following in User.following %}
        <ul class="list-group">
            <li class="list-group-item ">
                <div class="row">
                    <div class="col-2">
                        {% if following.avatar == null %}
                            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"  alt="Admin" class="rounded-circle" width="150">
                        {% endif %}

                        {% if following.avatar != null %}
                            <img src="{{following.avatar}}"  alt="Admin" class="rounded-circle" width="150">
                        {% endif %}

                    </div>
                    <div class="col-9">
                        <a href="{{ path('profile', {username: following.username}) }}">
                        {{  following.username }}
                        </a>
                    </div>
                    <div class="col-1">

                            <a href="{{ path('unfollowUser', {username: following.username}) }}">
                                <button class="btn btn-danger">Unfollow</button>
                            </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}



        </div>
    </div>
{% endblock %}

Symfony-Bloogt/templates/main/routes/account/chatList.html.twig
{% extends "main/routes/account/accountLayout.html.twig" %}

{% block body %}
    <h2>Chat list</h2>
    <ul class="list-group">
   {% for chat in chatList %}
        <li class="list-group-item">
            <span>
                {{ chat.createdAt}}

            </span>
            <span>
                {{ chat.lastMessage.message }}
            </span>

            <span>
               {% for user in chat.usersInvolved %}
                   {{ user.username }}
               {% endfor %}
            </span>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

Symfony-Bloogt/templates/main/routes/account/header.html.twig
<nav class="navbar navbar-expand-lg ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">

         {% if is_granted('ROLE_USER') -%}
            <li class="nav-item  text-right">
                <a class="nav-link" href="{{ path('profile', {username: app.user.username()}) }}">

                    {% if app.user.avatar == null %}
                        <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" class="headerProfilePic"/>
                    {% endif %}

                    {% if app.user.avatar != null %}
                        <img src="{{app.user.avatar}}" class="headerProfilePic"/>
                    {% endif %}

                </a>
            </li>





            <li class="nav-item ">
                <div class="nav-link">
               <span> {{app.user.username}} - </span><a class="" href="{{ path('app_logout') }}"> Desconectar</a>
                </div>
            </li>

         {% else -%}
         <li class="nav-item ">
             <a class="nav-link" href="{{ path('login') }}">Login</a>
         </li>
             <li class="nav-item ">
                 <a class="nav-link" href="{{ path('register') }}">Register</a>
             </li>

        {% endif -%}

        </ul>
    </div>
</nav>

Symfony-Bloogt/templates/main/routes/account/sendMessage.html.twig
{% extends "main/routes/account/accountLayout.html.twig" %}


{% block body %}
    <form action="{{ path('newChat') }}" >


        <div class="card bg-light mb-3">
            <div class="card-header">Send message </div>
            <div class="card-body">
                <div class="card-text "  class="form-group">



        {% if to is defined %}
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" value="{{to}}"/>
        {% elseif to is not defined %}
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" />
        {% endif %}
                    <label for="message">Message content</label>
                    <textarea class="form-control" name="message" placeholder="Message to send">

                    </textarea>

        <input type="submit" value="Send message" class="btn btn-block btn-primary"/>

                </div>
            </div>
        </div>

    </form>

{% endblock %}

Symfony-Bloogt/templates/main/routes/account/sidebar.html.twig
<div class="">

    <div class="card bg-light mb-3">
        <div class="card-header">Messages</div>
            <div class="card-text">
                <ul class="list-group">
                    <a href="{{ path('messages') }}">
                        <li class="list-group-item">Incoming messages</li>
                    </a>
                    <!--
                    <li class="list-group-item">Sent</li>
                    -->
                    <a href="{{ path('sendMessages') }}">
                        <li class="list-group-item">Send message</li>
                    </a>
                </ul>
            </div>
    </div>
    <div class="card bg-light mb-3">
        <div class="card-header">¿What's this?</div>
        <div class="card-body">
            <p class="card-text">This is the zone where you can control all about your profile, from private messages, to the people you follow...</p>
        </div>
    </div>



</div>

Symfony-Bloogt/templates/main/routes/account/subHeader.html.twig
<div>

    <a href="{{ path('account') }}"><button class="btn btn-secondary btn-lg">Home</button></a>
    <a href="{{ path('accountAportations') }}"><button class="btn btn-secondary btn-lg">My aportations</button></a>
    <a href="{{ path('accountNetwork') }}"><button class="btn btn-secondary btn-lg">My network</button></a>
    <button class="btn btn-secondary btn-lg">Private Messages</button>



    <div class="float-right">

        <a href="{{ path('profile', {username: app.user.username()}) }}">
            <button class="btn btn btn-light btn-lg">My profile</button>
        </a>
        <a href="{{ path('accountEdit') }}">
            <button class="btn btn btn-light btn-lg">My account</button>
        </a>
    </div>
</div>